name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: goran Packages Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Copy repository to OS environments
        uses: actions/checkout@v4

      - name: Install Go version 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test all packages
        run: go test ./...
