name: Run on Ubuntu with Go Ver 1.20

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copy repository to OS environments
        uses: actions/checkout@v4

      - name: Install go-version 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Test all packages
        run: go test ./...