name: Run on Ubuntu with Go Version 1.21

on:
  push:
    branches:
      - main

jobs:
  version_test: # Job name
    runs-on: ubuntu-latest
    name: Install Ubuntu

    steps:
      - name: Copy repository to OS environments
        uses: actions/checkout@v4

      - name: Install Go version 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test all packages
        run: go test ./...
